### ISSUE TITLE
Review and tidy CleanBC layer features

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-clean-bc#76]
> [Open in MURAL](https://app.mural.co/t/datasystemsandservices8142/m/datasystemsandservices8142/1674081183025?wid=0-1674673020838) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CleanBC JIRA to GH Integration - CITZ – BCDS – Data Systems and Services

**Comment by michaelpnelson** [comment]
The following changes were made to layer Electric Charging Stations in Canada:

Removed “Fuel Type Code” as each feature has the same “ELEC” value

Removed “Access Code” as each feature has the same “public” value (because we query on it to omit “private”)

Moved fields ending in “ - French” underneath their related non-French fields:

- Access Days Time
- BD Blends 
- Groups With Access Code
- Intersection Directions

Some date fields (for example, Date Last Confirmed and Open Date) appear to use Unix epoch time and are not human-readable (example: 1654819200000). I think we should confirm with the customer that these fields are useful. If so, I will need to look into whether we can format those values. Other dates fields use a readable format (example: 2022-04-26 16:04:15 UTC from field Updated At).

Changes implemented in pull request [Removed, reordered some Charging Stations layer fields by michaelpnelson · Pull Request #77 · bcgov/smk-clean-bc](https://github.com/bcgov/smk-clean-bc/pull/77) .
