### ISSUE TITLE
Replace "Electric Charging Stations in Canada" Esri feature layer with NREL GeoJson layer

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-clean-bc#84]
> [Open in MURAL](https://app.mural.co/t/datasystemsandservices8142/m/datasystemsandservices8142/1674081183025?wid=0-1676495359141) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CleanBC JIRA to GH Integration - CITZ – BCDS – Data Systems and Services

**Comment by NicoledeGreef** [comment]
MVP

**Comment by michaelpnelson** [comment]
The layer was changed to a vector/GeoJSON type. It consumes features from NREL’s API (All Stations  API | NREL: Developer Network ) using Beth’s API key.

Feature attributes in the new layer mostly correlate to attributes in the Esri-hosted layer. I’ve maintained the existing order of correlating attributes. Attributes that appear in the new layer and not the old layer are ordered further down the list.

I’ve maintained the combination of “EV Network” and “EV Network Web” attributes, using the value of the latter in a link with the link label being the value of the former.

I’ve changed some feature attributes to not be visible since they are implicit (we query on these and they will all have the same value): “Country” (CA), “State” (BC), “Fuel Type Code” (ELEC), “Access Code” (public). “ID” is also not visible, as the ID field was requested to be hidden in the other layers.

Unfortunately, now that this is a GeoJSON layer, it appears prone to the same ordering issue we saw between the other two GeoJSON layers, and this layer sometimes appears on top. This is being addressed in another issue.

Outcome
Changes are implemented in pull request [Change Charging Stations layer from Esri Feature to GeoJSON by michaelpnelson · Pull Request #94 · bcgov/smk-clean-bc](https://github.com/bcgov/smk-clean-bc/pull/94) .

**Comment by michaelpnelson** [comment]
Suggestions for review:

Please let us know if you'd like to change the layer attributes that display when we click on a feature. We can easily change the visibility (hidden or not), order, and title/label of the attributes in this layer. We can't easily format the values - depending on the format change, we'd likely need to make an update to SMK for it.

@rustyjux also has some suggestions in a review comment: https://github.com/bcgov/smk-clean-bc/pull/94#issuecomment-1443905273.
